### ISSUE TITLE
unable to build on windows 7, latest nodejs, vs2015

### ISSUE THREAD

**Issue by fholzer** [qesuto/node-krb5#14]
Tried using node 4.0, 4.4.7 and latest (6.2.2) on Windows 7 x86_64 with Visual Studio 20015 (Update 3)

        $npm install
        npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
        npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
        npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
        npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

        > node-krb5@0.0.6 install C:\Users\fholzer\Documents\git\node-krb5
        > node-gyp rebuild

        C:\Users\fholzer\Documents\git\node-krb5>if not defined npm_config_node_gyp (node "C:\Users\fholzer\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
        Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
          krb5.cc
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)': function template has already been defined [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(319): note: see declaration of 'Nan::imp::NanEnsureHandleOrPersistent'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(346): error C2995: 'v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)': function template has already been defined [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(334): note: see declaration of 'Nan::imp::NanEnsureLocal'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(560): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          c:\users\fholzer\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(560): error C2065: 'GCEpilogueCallback': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(561): error C2146: syntax error: missing ')' before identifier 'callback' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(561): error C2143: syntax error: missing ';' before '{' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(561): error C2447: '{': missing function header (old-style formal list?) [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(566): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          c:\users\fholzer\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(566): error C2065: 'GCEpilogueCallback': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(566): error C2146: syntax error: missing ')' before identifier 'callback' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(566): error C2143: syntax error: missing ';' before '{' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(566): error C2447: '{': missing function header (old-style formal list?) [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(571): error C2039: 'GCPrologueCallback': is not a member of 'v8::Isolate' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          c:\users\fholzer\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(571): error C2065: 'GCPrologueCallback': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(572): error C2146: syntax error: missing ')' before identifier 'callback' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(572): error C2143: syntax error: missing ';' before '{' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(572): error C2447: '{': missing function header (old-style formal list?) [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(577): error C2039: 'GCPrologueCallback': is not a member of 'v8::Isolate' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          c:\users\fholzer\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(577): error C2065: 'GCPrologueCallback': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(577): error C2146: syntax error: missing ')' before identifier 'callback' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(577): error C2143: syntax error: missing ';' before '{' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(577): error C2447: '{': missing function header (old-style formal list?) [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(757): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(757): error C2039: 'FreeCallback': is not a member of 'node' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\.node-gyp\6.2.2\include\node\node_object_wrap.h(8): note: see declaration of 'node'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(757): error C2061: syntax error: identifier 'FreeCallback' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(761): error C2065: 'callback': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(761): error C2065: 'hint': undeclared identifier [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(768): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\.node-gyp\6.2.2\include\node\node_buffer.h(46): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,std::size_t)'
          C:\Users\fholzer\.node-gyp\6.2.2\include\node\node_buffer.h(34): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(768): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(772): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(772): note: No constructor could take the source type, or constructor overload resolution was ambiguous
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(779): error C2039: 'Use': is not a member of 'node::Buffer' [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
          C:\Users\fholzer\.node-gyp\6.2.2\include\node\node_buffer.h(11): note: see declaration of 'node::Buffer'
        C:\Users\fholzer\Documents\git\node-krb5\node_modules\nan\nan.h(779): error C3861: 'Use': identifier not found [C:\Users\fholzer\Documents\git\node-krb5\build\krb5.vcxproj]
        gyp ERR! build error
        gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
        gyp ERR! stack     at ChildProcess.onExit (C:\Users\fholzer\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
        gyp ERR! stack     at emitTwo (events.js:106:13)
        gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
        gyp ERR! System Windows_NT 6.1.7601
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fholzer\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
        gyp ERR! cwd C:\Users\fholzer\Documents\git\node-krb5
        gyp ERR! node -v v6.2.2
        gyp ERR! node-gyp -v v3.3.1
        gyp ERR! not ok

        npm WARN node-krb5@0.0.6 No license field.
        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fholzer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
        npm ERR! node v6.2.2
        npm ERR! npm  v3.10.3
        npm ERR! code ELIFECYCLE
        npm ERR! node-krb5@0.0.6 install: `node-gyp rebuild`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-krb5@0.0.6 install script 'node-gyp rebuild'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the node-krb5 package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node-gyp rebuild
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs node-krb5
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls node-krb5
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\fholzer\Documents\git\node-krb5\npm-debug.log

Any help apprechiated!

Regard,
Ferdinand

**Comment by evil-shrike** [comment]
I have the same on Windows 10, tried with vs2013 and vs2015 tools.
