### ISSUE TITLE
Does not build against node 0.12

### ISSUE THREAD

**Issue by sibartlett** [qesuto/node-krb5#8]
Build output:

```
2260 verbose linkStuff [ false,
2260 verbose linkStuff   false,
2260 verbose linkStuff   false,
2260 verbose linkStuff   '/Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp/node_modules' ]
2261 info linkStuff minimist@0.0.8
2262 verbose linkBins minimist@0.0.8
2263 verbose linkMans minimist@0.0.8
2264 verbose rebuildBundles minimist@0.0.8
2265 info postinstall fstream@0.1.31
2266 info install minimist@0.0.8
2267 info postinstall minimist@0.0.8
2268 verbose unlock done using /Users/danieldaks1/.npm/_locks/fstream-7b3158eabfbb53d0.lock for /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/fstream
2269 verbose unlock done using /Users/danieldaks1/.npm/_locks/minimist-a3bbb6d35ce1b155.lock for /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp/node_modules/minimist
2270 verbose about to build /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5/node_modules/node-gyp/node_modules/mkdirp
                       ~~~~~ ^
../src/krb5.cc:111:30: error: no member named 'New' in 'v8::String'
                return scope.Close(String::New("wrong arguments"));
                                   ~~~~~~~~^
../src/krb5.cc:116:51: error: no member named 'AsciiValue' in 'v8::String'
        authStruct->principal = new std::string(*String::AsciiValue(Local<String>::Cast(args[0])));
                                                 ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: *** [Release/obj.target/krb5/src/krb5.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danieldaks1/src/letschat/node_modules/lets-chat-kerberos/node_modules/passport-kerberos/node_modules/node-krb5
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "lets-chat-kerberos"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-krb5@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-krb5@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-krb5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-krb5
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danieldaks1/src/letschat/npm-debug.log
```

**Comment by hhaidar** [comment]
https://github.com/rvagg/nan

**Comment by qesuto** [comment]
guys, I'm pretty busy on other stuff right now. nan seemed promising, but it didn't work as advertised. Feel free to post a pull request or branch it to fit your needs. hope to be able to work on it eventually.
