### ISSUE TITLE
Build fails to find krb5.h header, even though it exists

### ISSUE THREAD

**Issue by adnelson** [qesuto/node-krb5#9]
I'm getting the following output when I try to `npm install`. My platform is arch linux, `3.17.3-1-ARCH`.

```
npm install
|
> node-krb5@0.0.5 install /home/anelson/workspace/node/node-krb5
> node-gyp rebuild

make: Entering directory '/home/anelson/workspace/node/node-krb5/build'
  CXX(target) Release/obj.target/krb5/src/krb5.o
../src/krb5.cc:6:18: fatal error: krb5.h: No such file or directory
 #include <krb5.h>
                  ^
compilation terminated.
krb5.target.mk:86: recipe for target 'Release/obj.target/krb5/src/krb5.o' failed
make: *** [Release/obj.target/krb5/src/krb5.o] Error 1
make: Leaving directory '/home/anelson/workspace/node/node-krb5/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.17.3-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/anelson/workspace/node/node-krb5
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.17.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.9
npm ERR! code ELIFECYCLE
npm ERR! node-krb5@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-krb5@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-krb5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-krb5
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anelson/workspace/node/node-krb5/npm-debug.log
```

The file `krb5.h` is present in `/usr/include`, which is certainly a folder than any sensible compiler should be checking. I'm not sure if this is an issue with this library or with `node-gyp`.

**Comment by adnelson** [comment]
This was a problem on my end... No worries! Closing this.
